# Test urls
login_url: 'https://test-stand.gb.ru/gateway/login'
posts_url: 'https://test-stand.gb.ru/api/posts'

# Auth data
username: '4stud'
password: 'e442630e84'

# Test data
## Step 1: Finding item
postitve_answer: 'test_title'

## Step 2: Create post
title: test_title
description: test_description
content: test_content
description_answer: test_description